spring.application.name=dws
spring.datasource.url=jdbc:mysql://localhost:3306/dws
spring.datasource.username=root
spring.datasource.password=admin@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajeshwaren231@gmail.com
spring.mail.password=ceavpyxhdgpfcacj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true